WebApp/Controllers/AddNewsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using BAL.Interfaces;
using Common;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Model.DTO;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class AddNewsController : BaseWebController
	{
        IHostingEnvironment appEnvironment;
        private readonly ICourseManager courseManager;
        private readonly INewsManager newsManager;

        public AddNewsController(ICourseManager courseManager, INewsManager newsManager,
            IHostingEnvironment appEnvironment)
        {
            this.newsManager = newsManager;
            this.courseManager = courseManager;
            this.appEnvironment = appEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult News(int page = 1, int id = 0)
        {
            int pageSize = 8; 
            List<NewsDTO> news;
            if (id == 0)
            {
                news = newsManager.GetAll().Reverse().ToList();
            }
            else
            {
                news = newsManager.Get().Where(e => e.CourseId == id).Reverse().ToList();
            }
            var count = news.Count();
            var items = news.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            var courses = courseManager.GetAll().ToList();

            PageViewModel NewsPageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel
            {
                NewsPageViewModel = NewsPageViewModel,
                News = items,
                Courses = courses
            };
            return View(viewModel);
        }
        [HttpPost("UploadFiles")]
        public async Task<IActionResult> Post(IFormFile files, string Text, string Title, string Course)
        {
            // full path to file in temp location
            var filePath = "/images/" + files.FileName;
            

            using (var fileStream = new FileStream(appEnvironment.WebRootPath + filePath, FileMode.Create))
            {
                await files.CopyToAsync(fileStream);
            }
            if (filePath == null)
                filePath = " ";
            var course = courseManager.Get().Where(e => e.Name == Course).FirstOrDefault();

            NewsDTO newsDTO = new NewsDTO()
            {
                Text = Text,
                Title = Title,
                ImagePath = filePath,
                Day = DateTime.Today.Day,
                Month = Enum.GetName(typeof(MonthEnum),
                DateTime.Today.Month - 1),
                CourseId = course.Id
            };

            newsManager.Insert(newsDTO);

            var news = newsManager.GetAll().ToList();
            var courses = courseManager.GetAll().ToList();
            return RedirectToAction("News");

        }
        public void AddArticle()
        {


        }

        public void DeleteOrRecoverArticle(NewsDTO newsDTO)
        {
            newsManager.DeleteOrRecover(newsDTO.Id);
        }

        public void UpdateArticle(NewsDTO newsDTO)
        {
            newsManager.Update(newsDTO);
        }
        public IActionResult ShowNews(int id)
        {
            var news = newsManager.Get().Where(e => e.Id == id).FirstOrDefault();
            return View(news);
        }
    }
}

WebApp/Controllers/AdminPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using WebApp.Models;
using WebApp.ViewModels;
using Model.DB;
using Model.DTO;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using BAL.Interfaces;
using BAL.Managers;
using Model.DB.Code;
using Model.DTO.CodeDTO;
using Model.Entity;

namespace WebApp.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminPanelController : BaseWebController
	{
        private readonly UserManager<User> userManager;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly IExerciseManager exerciseManager;
        private readonly ICourseManager courseManager;
        private readonly ICodeManager codeManager;

        IMapper mapper;

        public AdminPanelController(ICodeManager codeManager, UserManager<User> userManager, RoleManager<IdentityRole> roleManager, IMapper mapper, IExerciseManager exerciseManager, ICourseManager courseManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.codeManager = codeManager;
            this.mapper = mapper;
            this.exerciseManager = exerciseManager;
            this.courseManager = courseManager;
        }
        

        public IActionResult Users()
        {
            var t = this.mapper.Map<List<UserDTO>>(this.userManager.Users.ToList());
            return View(t);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await this.userManager.FindByIdAsync(id);
            var code = codeManager.Get().Where(e => e.UserId == user.Id).FirstOrDefault();
            
            if (user != null)
            {
                codeManager.DeleteHistoryLst(code);
                codeManager.DeleteCode(code);
                await this.userManager.DeleteAsync(user);
            }
            return RedirectToAction("Users");
        }


        
       
        public IActionResult Roles() => View(this.roleManager.Roles.ToList());

        

        public IActionResult CreateRole() => View();
        [HttpPost]
        public async Task<IActionResult> CreateRole(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await this.roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Roles");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }
        
        public async Task<IActionResult> DeleteRole(string id)
        {
            IdentityRole role = await this.roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await this.roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Roles");
        }

        public async Task<IActionResult> DeleteRoleFromUser(string userId, List<string> roles)
        {
            User user = await this.userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await this.userManager.GetRolesAsync(user);
                var addedRoles = roles.Except(userRoles);

                await this.userManager.RemoveFromRolesAsync(user, addedRoles);

                return RedirectToAction("EditRole");
            }
            return NotFound();
        }

        public async Task<IActionResult> EditRole(string userId)
        {
            User user = await this.userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await this.userManager.GetRolesAsync(user);
                var allRoles = this.roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> EditRole(string userId, List<string> roles)
        {
            User user = await this.userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await this.userManager.GetRolesAsync(user);
                var allRoles = this.roleManager.Roles.ToList();
                var addedRoles = roles.Except(userRoles);
                var removedRoles = userRoles.Except(roles);
                await this.userManager.AddToRolesAsync(user, addedRoles);
                await this.userManager.RemoveFromRolesAsync(user, removedRoles);
                return RedirectToAction("Users");
            }

            return NotFound();
        }

    }
}

WebApp/Controllers/UserRatingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using WebApp.Models;
using WebApp.ViewModels;
using WebApp.ViewModels.UserCodeReview;
using Model.DB;
using Model.DTO;
using Microsoft.AspNetCore.Authorization;
using DAL.Interface;
using BAL.Interfaces;
using WebApp.ViewModels.CoursesViewModels;
using AutoMapper;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApp.Controllers
{
    public class UserRatingController : BaseWebController
	{
       
        private readonly IUserRatingManager userRatingManager;
        private readonly IMapper mapper;

        private readonly UserManager<User> userManager;

        public UserRatingController(IUserRatingManager userRatingManager, IMapper mapper, UserManager<User> userManager)
        {
            this.userRatingManager = userRatingManager;
            this.mapper = mapper;
            this.userManager = userManager;
        }

       
        public IActionResult Index()
        {
            var userList = userRatingManager.GetAll(userManager);
            return View(userList);
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

@inject IHtmlLocalizer<SharedRes> SharedLocalizer
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/css/normalize.css" rel="stylesheet" />
    <link href="~/css/component.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/codemirror.css" />
    <link rel="stylesheet" href="~/css/StarRating.css" />
    <!-- <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>-->
    <script src="~/js/jquery.tinymce.min.js"></script>
    <script src="~/js/tinymce.min.js"></script>
    <script src="~/js/codemirror.js"></script>
    <script src="~/js/matchbrackets.js"></script>
    <script src="~/js/continuecomment.js"></script>
    <script src="~/js/clike.js"></script>
    <script src="~/js/jquery.tinymce.min.js"></script>
    <script src="~/js/StarRating.js"></script>


    <title>@ViewData["Title"] - WebApp</title>

    <style>
        a:hover {
            text-decoration: none;
        }

        .gn-menu-main {
            background-color: #0d0804;
            scrollbar-face-color: #ffffff;
        }

        .gn-icon-menu::before {
            background: #ffffff;
            box-shadow: 0 3px #0d0804, 0 -6px #ffffff, 0 -9px #0d0804, 0 -12px #ffffff;
        }

        .gn-icon-menu.gn-selected::before {
            background: #ffffff;
            box-shadow: 0 3px #0d0804, 0 -6px #ffffff, 0 -9px #0d0804, 0 -12px #ffffff;
        }

        .gn-menu-main li {
            border: #0d0804;
        }

            .gn-menu-main li:focus {
                background-color: #ffffff;
            }

        .gn-menu-wrapper {
            background-color: #0d0804;
            color: #0d0804;
        }

        .gn-icon {
            background-color: #0d0804;
            color: #ffffff;
        }

        .gn-menu-main a {
            color: #ffffff;
        }

        .gn-trigger a:after {
            color: #ffffff;
        }
        .contacts{
            font-size:21px;
        }
    </style>
</head>

<body>
    <div>
        <ul id="gn-menu" class="gn-menu-main navbar-fixed-top">
            <li class="gn-trigger">
                <a class="gn-icon gn-icon-menu"><span>Menu</span></a>
                <nav class="gn-menu-wrapper">
                    <div class="gn-scroller">
                        <ul class="gn-menu">



                            @if (User.IsInRole("Administrator"))
                            {
                                <li>
                                    <a class="gn-icon gn-icon-cog" asp-controller="AdminPanel" asp-action="Users">
                                        @SharedLocalizer["AdminPanel"]
                                    </a>
                                </li>
                            }
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li>
                                    <a class="gn-icon gn-icon-article" asp-controller="AddNews" asp-action="News">
                                        @SharedLocalizer["News"]
                                    </a>
                                </li>
                            }
                            @if (User.IsInRole("Teacher"))
                            {
                                <li>
                                    <a class="gn-icon gn-icon-earth" asp-controller="ExerciseManagement" asp-action="Index">
                                        @SharedLocalizer["Tasks"]
                                    </a>
                                </li>
                            }
                            <li>
                                <a class="gn-icon gn-icon-earth" asp-controller="UserRating" asp-action="Index">
                                    @SharedLocalizer["Ratings"]
                                </a>
                            </li>
                            <li><a class="gn-icon gn-icon-earth" asp-controller="CourseManagement" asp-action="Index">@SharedLocalizer["Courses"]</a></li>
                            @if (User.Identity.IsAuthenticated)
                            {

                                <li><a class="gn-icon gn-icon-archive" asp-controller="CodeHistory" asp-action="History">@SharedLocalizer["CodeHistory"]</a></li>

                            }
                            @if (User.IsInRole("Administrator") || User.IsInRole("Teacher"))
                            {
                                <li><a class="gn-icon glyphicon glyphicon-envelope contacts" style="padding-top:20px;padding-bottom:20px; padding-left:2px;" asp-controller="EmailMessages" asp-action="Index">@SharedLocalizer["Messages"]</a></li>

                            }
                            @if (!User.IsInRole("Administrator") && !User.IsInRole("Teacher"))
                            {
                                <li>
                                    <a class="gn-icon glyphicon glyphicon-envelope contacts" 
                                       style="padding-top:20px;padding-bottom:20px;" asp-controller="EmailMessages" 
                                       asp-action="GetEmail">@SharedLocalizer["Contacts"]</a>
                                </li>
                            }
                        </ul>
                    </div>
                </nav>
            </li>
            <li>
                <a asp-area="" asp-controller="Home" asp-action="Index" style="font-size: 20px">@SharedLocalizer["SoftServe"]</a>
            </li>
            @await Html.PartialAsync("_LoginPartial")
        </ul>
        <header></header>
        <br />
        <br />
        <div class="container body-content" style="margin-top: 30px">
            @RenderBody()
        </div>
    </div>

    <script src="~/js/modernizr.custom.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/classie.js"></script>
    <script src="~/js/gnmenu.js"></script>
    <script src="~/js/site.js"></script>
    <script>
        new gnMenu(document.getElementById('gn-menu'));
    </script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    // получаем сервис IRequestCultureFeature
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    // получаем список поддерживаемых культур
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
    
}
<style>
    select {
        background-color: #ffffff;
    }
    .deff {
        font-size: 13px;
        font-family: 'Lato', Arial, sans-serif;
        line-height: 30px;
        color: black;
        text-transform: uppercase;
        letter-spacing: 1px;
        font-weight: bold;
        display: block;
        height: 100%;
        color: #ffffff;
        text-decoration: none;
    }
    .deff-language {
        padding-top: 15px;
        margin-left: 15px;
    }
    .dropdown-lang {
        font-size: 15px;
        color: black;
        margin-right: 15px
    }
    
</style>

<form  asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path"
       method="post" class="form-horizontal deff deff-language">
    @Localizer["Language:"]
    <select class="dropdown-lang" name="culture" onchange="this.form.submit();"
            asp-for="@requestCulture.RequestCulture.UICulture.Name"
            asp-items="cultureItems">
        
    </select>
</form>