WebApp/Controllers/CodeController.cs
using BAL.Interfaces;
using BAL.Managers;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Model.DB;
using WebApp.ViewModels;
using WebApp.ViewModels.UserCodeReview;
using Model.DTO.CodeDTO;
using Microsoft.AspNetCore.Authorization;
using RestSharp;
using Microsoft.Extensions.Configuration;

namespace WebApp.Controllers
{
    [Authorize]
    public class CodeController : BaseWebController
	{
        private CodeManager codeManager;
        private IExerciseManager exerciseManager;
        private UserManager<User> userManager;
        private readonly IConfiguration configuration;

        public CodeController(CodeManager codeManager, IExerciseManager exerciseManager, UserManager<User> userManager, IConfiguration configuration)
        {
            this.codeManager = codeManager;
            this.exerciseManager = exerciseManager;
            this.userManager = userManager;
            this.configuration = configuration;
        }
        public IActionResult Index(UserCodeDTO model)
        {
            if (!ModelState.IsValid)
            {
                return View("../Home/Index");
            }
            var exercise = exerciseManager.GetById(model.ExerciseId);
            return View(new CodeStartViewModel() {
                UserCodeDTO = codeManager.BuildCodeModel(model),
                ExerciseTaskText = exercise.TaskTextField
        });
        }

        [HttpPost]
        public string GetCode(UserCodeDTO model)
        {
            return model.CodeText == null ? "Write some code" : codeManager.ExecuteCode(model);
        }


        [HttpPost]
        public string ExecuteOnFlyCode(UserCodeDTO model)
        {
            return model.CodeText == null ? "Write some codeeeee" : codeManager.GetOnFlyCode(model);
        }

        [HttpPost]
        public string TestRun(TestRunViewModel code)
        {
            return code == null ? "Write some codeeeee" : codeManager.ExecuteOnFlyCode(code.TestRunCode);
        }

        [HttpPost]
        public IActionResult SetCodeStatus(UserCodeViewModel model)
        {
            var code = codeManager.UserCodeByExId(model.UserId, model.ExerciseId);
            if (code != null)
            {
                codeManager.SetCodeStatus(code.Id, code.UserId);
            }
            return RedirectToAction("Index", "CourseManagement");
        }

        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public IActionResult CodeReview(int id)
        {
            var client = new RestClient(configuration.GetConnectionString("WebAppRouteAPI"));
            var request = new RestRequest("api/CodeAPI/{id}", Method.GET);
            request.AddUrlSegment("id", id);
            IRestResponse<UserCodeReviewViewModel> response = client.Execute<UserCodeReviewViewModel>(request);
            return View(response.Data);
        }

        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public IActionResult CodeMarking(UserCodeReviewViewModel model)
        {
            var client = new RestClient(configuration.GetConnectionString("WebAppRouteAPI"));
            var request = new RestRequest("api/CodeAPI", Method.POST);
            request.AddParameter("userCodeId", model.UserCodeDTO.Id);
            request.AddParameter("userCodeMark", model.UserCodeDTO.Mark);
            request.AddParameter("userCodeTeachersComment", model.UserCodeDTO.TeachersComment);
            request.AddParameter("userCodeDTOUserId", model.UserCodeDTO.UserId);
            IRestResponse response = client.Execute(request);
            return RedirectToAction("Index", "ExerciseManagement");
        }

    }
}

WebApp/Controllers/ExerciseManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using WebApp.Models;
using WebApp.ViewModels;
using WebApp.ViewModels.UserCodeReview;
using Model.DB;
using Model.DTO;
using Microsoft.AspNetCore.Authorization;
using DAL.Interface;
using BAL.Interfaces;
using WebApp.ViewModels.CoursesViewModels;
using AutoMapper;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApp.ApiControllers;
using System.Net.Http;
using RestSharp;
using Microsoft.Extensions.Configuration;

namespace WebApp.Controllers
{
    public class ExerciseManagementController : BaseWebController
	{
        private readonly IExerciseManager exerciseManager;
        private readonly ICourseManager courseManager;
        private readonly UserManager<User> userManager;
        private readonly ICommentManager commentManager;
        private readonly IConfiguration configuration;
        private readonly ICodeManager codeManager;
        private readonly IMapper mapper;

        public ExerciseManagementController(IExerciseManager exerciseManager, ICourseManager courseManager,
                                            UserManager<User> userManager, ICodeManager codeManager , IMapper mapper, ICommentManager commentManager, IConfiguration configuration)
        {
            this.exerciseManager = exerciseManager;
            this.courseManager = courseManager;
            this.userManager = userManager;
            this.commentManager = commentManager;
            this.configuration = configuration;
            this.mapper = mapper;
            this.codeManager = codeManager;
        }

        [Authorize(Roles = "Teacher")]
        public IActionResult Index()
        {

            var exerciseList = exerciseManager.GetAll();
            return View(exerciseList);
        }


        [Authorize(Roles = "Teacher")]
        public IActionResult Create()
        {
            var courseList = courseManager.Get(x => x.IsActive).ToList();
            return View(new CreateExerciseViewModel()
            {
                CourseList = courseList,
                TestCases = "using NUnit.Framework;"
            });
        }

        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public IActionResult Create(CreateExerciseViewModel model)
        {
            var user = userManager.GetUserAsync(HttpContext.User).Result;

            if (ModelState.IsValid)
            {
                var course = courseManager.GetById(model.CourseId);
                ExerciseDTO task = new ExerciseDTO
                {
                    CourseId = model.CourseId,
                    Course = course.Name,
                    TaskName = model.TaskName,
                    TaskTextField = model.TaskTextField,
                    TaskBaseCodeField = model.TaskBaseCodeField,
                    TestCasesCode = model.TestCases,
                    TeacherId = user.Id,
                    Rating = 0,
                    CreateDateTime = DateTime.Now,
                    UpdateDateTime = DateTime.Now
                };
                exerciseManager.Insert(task);
            }
            return RedirectToAction("Index", "ExerciseManagement");
        }


        public IActionResult TaskView(int id)
        {

            var client = new RestClient(configuration.GetConnectionString("WebAppRouteAPI"));
            var request = new RestRequest("api/ExerciseManagementAPI/{id}", Method.GET);
            request.AddUrlSegment("id", id);
            request.ReadWriteTimeout = 500;
            IRestResponse<GetExerciseViewModel> response = client.Execute<GetExerciseViewModel>(request);
            return View(response.Data);
        }


        [Authorize(Roles = "Teacher")]
        public IActionResult Update(int id)
        {
            var courseList = courseManager.Get(g => g.IsActive).ToList();
            var task = exerciseManager.GetById(id);
            if (task == null)
            {
                return NotFound();
            }
            return View(new UpdateExerciseViewModel()
            {
                Id = id,
                CourseList = courseList,
                TaskName = task.TaskName,
                TaskTextField = task.TaskTextField,
                TaskBaseCodeField = task.TaskBaseCodeField,
                TestCases = task.TestCasesCode
            });

        }

        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public IActionResult Update(UpdateExerciseViewModel model)
        {
            var course = courseManager.GetById(model.CourseId);
            if (ModelState.IsValid)
            {

                    exerciseManager.Update(model.Id, model.TaskName, model.TaskTextField,
                                       model.TaskBaseCodeField, model.CourseId,
                                       course.Name, DateTime.Now, model.TestCases);
            }
            return RedirectToAction("Index", "ExerciseManagement");
        }


        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public IActionResult DeleteOrRecover(int id)
        {
            exerciseManager.DeleteOrRecover(id);
            return RedirectToAction("Index", "ExerciseManagement");
        }

        [HttpGet]
        [Authorize(Roles = "Teacher")]
        public IActionResult ExerciseSolutionsIndex(int id)
        {
            List<UserCodeListUnitViewModel> codesList = new List<UserCodeListUnitViewModel>();
            var solutionsList = codeManager.Get(c => c.ExerciseId == id && (c.CodeStatus == Model.Entity.CodeStatus.Done || c.CodeStatus == Model.Entity.CodeStatus.Appreciated ));
            if (solutionsList != null)
            {

                foreach (var elem in solutionsList)
                {
                    codesList.Add(new UserCodeListUnitViewModel
                    {
                        codeUnit = elem,
                        UserName = userManager.FindByIdAsync(elem.UserId).Result.UserName
                    });
                }

            }
            UserCodeListViewModel model = new UserCodeListViewModel { userCodeList = codesList };
            return View(model);
        }


        [HttpPost]
         [Authorize(Roles = "Teacher")]
        public IActionResult ExerciseSolutionsIndex(UserCodeListViewModel model)
        {
            var b = model.userCodeList;

            return RedirectToAction("ExerExerciseSolutionsIndex", "ExerciseManagement");

        }



    }
    }

WebApp/Views/ExerciseManagement/Create.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@inject IHtmlLocalizer<SharedRes> SharedLocalizer

@model WebApp.ViewModels.CreateExerciseViewModel;
@{
    ViewBag.Title = "Add Task";
}
<link rel="stylesheet" href="~/css/codemirror.css" />
<script src="~/js/codemirror.js"></script>
<script src="~/js/matchbrackets.js"></script>
<script src="~/js/continuecomment.js"></script>
<script src="~/js/clike.js"></script>
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script src="~/js/jquery.min.js"></script>
<link rel="stylesheet" href="~/css/site.css" />

<form asp-action="Create" asp-controller="ExerciseManagement" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">

        <label class="control-label">@SharedLocalizer["CourseName"] *</label>
        <select asp-for="CourseId" asp-items="@(new SelectList(Model.CourseList, "Id" , "Name"))" class="form-control" required></select>
        <label class="control-label">@SharedLocalizer["TaskName"] *</label>
        <input asp-for="TaskName" type="text" class="form-control" required />
    </div>
    <div class="form-group">
        <label class="control-label">@SharedLocalizer["Task"]:</label>
        <textarea asp-for="TaskTextField" id="MCE"></textarea>
    </div>
    <div>
        <button type="button" class="btn btn-success" id="runCode">►@SharedLocalizer["Run"]</button>
    </div>
    <div class="row">
        <div class="col-md-6">
            <label class="control-label">@SharedLocalizer["BaseCode"]:</label>
            <textarea asp-for="TaskBaseCodeField" id="taskBaseCodeField" class="col-md-12" style="height: 400px; width: 100%;"></textarea>
        </div>

        <div>
            <label class="control-label">@SharedLocalizer["TestCasesCode"]:</label>
            <textarea asp-for="TestCases" id="testCasesCodeField" class="col-md-12" style="height: 400px; width: 100%;"></textarea>
        </div>
    </div>
    <div>
        <textarea id="result" style="padding: 10px; border-color: black; border: 1px solid; height: 100%; width: 100%; background-color: white" readonly="readonly"></textarea>
    </div>
    <br />
    <div class="form-group">
        <button type="submit" class="btn btn-default">@SharedLocalizer["Add"]</button>
    </div>
</form>


<br />
<h6>@SharedLocalizer["Required"]</h6>
@section Scripts{
    <script>

        tinymce.init({
            selector: '#MCE',
            plugins: [
                'advlist autolink list link image charmap print preview hr anchor pagebreak',
                'searchreplace wordcount visualblocks visualchars code fullscreen',
                'insertdatetime media nonbreaking save table contextmenu directionality',
                'emoticons template paste textcolor colorpicker textpattern imagetools image'
            ],
            toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
            toolbar2: 'print preview media | forecolor backcolor emotions | code',
            image_title: true,
            automatic_uploads: true,
            file_picker_types: 'image',
            file_picker_callback: function (cb, value, meta) {
                var input = document.createElement('input');
                input.setAttribute('type', 'file');
                input.setAttribute('accept', 'image/*');
                input.onchange = function () {
                    var file = this.files[0];

                    var reader = new FileReader();
                    reader.onload = function () {
                        var id = 'blobid' + (new Date()).getTime();
                        var blobCache = tinymce.activeEditor.editorUpload.blobCache;
                        var blobInfo = blobCache.create(id, file, base64);
                        blobCache.add(blobInfo);

                        cb(blobInfo.blobUri(), { title: file.name });
                    };
                    reader.readAsDataURL(file);
                };
                input.click();
            }
        });


        window.onload = function () {
            var editableCodeMirror = CodeMirror.fromTextArea(document.getElementById('taskBaseCodeField'), {
                mode: "text/x-csrc",
                theme: "default",
                lineNumbers: true
            });
            var editableTestCasesCodeMirror = CodeMirror.fromTextArea(document.getElementById('testCasesCodeField'), {
                mode: "text/x-csrc",
                theme: "default",
                lineNumbers: true
            });

            $('#runCode').click(
                function () {
                    $('#result').html('');
                    var code = new Object();
                    code.TestRunCode = editableTestCasesCodeMirror.getValue();
                    code.TestRunCode += editableCodeMirror.getValue();
                    $.ajax({
                        type: "POST",
                        url: "/Code/TestRun",
                        data: code,
                        success: function (data) {
                            $("#result").html(data);
                        }
                    });
                }
            );
        };
    </script>}

WebApp/Views/ExerciseManagement/ExerciseSolutionsIndex.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@inject IHtmlLocalizer<SharedRes> SharedLocalizer

@model WebApp.ViewModels.UserCodeReview.UserCodeListViewModel;
@{
    ViewBag.Title = "Task List";
}

@if (Model.userCodeList==null)
{
   <h4>There areno solutions yet </h4>
}
else
{
<table class="table">
    <tr>
        <td>@SharedLocalizer["User"]</td>
        <td>@SharedLocalizer["Solution"]</td>
    </tr>
    @foreach (var code in Model.userCodeList)
    {
       
            <tr>
                    <td>@code.UserName</td>
                    <td>@code.codeUnit.CodeStatus</td>
                    
                    <td>
                        @if (User.IsInRole("Teacher"))
    {
                        <form  asp-action="CodeReview" asp-controller="Code">
                            <input type="hidden" name="id" value="@code.codeUnit.Id" />
                            <button type="submit" class="btn btn-sm btn-success"> @SharedLocalizer["Review"] </button>
                        </form>
}
                    </td>
            </tr>
       
    }
</table>
}

WebApp/Views/ExerciseManagement/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@inject IHtmlLocalizer<SharedRes> SharedLocalizer

@model IEnumerable<Model.DTO.ExerciseDTO>
@{
    ViewBag.Title = "Task List";
}

@if (User.IsInRole("Teacher"))
{
    <h4 style="margin-top: 15px"><a asp-action="Create" class="btn btn-sm btn-default">@SharedLocalizer["AddTask"]</a></h4>
}
<table class="table">
    <tr>
                @if (User.IsInRole("Teacher"))
                {
                    <td>@SharedLocalizer["TaskName"]</td>
                    <td>@SharedLocalizer["CreateDate"]</td>
                    <td>@SharedLocalizer["UpdateDate"]</td>
                    <td>@SharedLocalizer["CourseName"]</td>
                    <td></td>
                }
        </tr>
    @foreach (var task in Model)
    {
        @if (!task.IsDeleted)
        {
            <tr>
                <td>
                    <a id="bluhighl" asp-action="TaskView" asp-route-id="@task.Id">@task.TaskName</a></td>
                
                @if (User.IsInRole("Teacher"))
                {
                    
                    <td>@task.CreateDateTime.ToString("dd/MM/yyyy")</td>
                    <td>@task.UpdateDateTime.ToString("dd/MM/yyyy")</td>
                }
                    <td>@task.Course </td>
                <td>
                    @if (User.IsInRole("Teacher"))
    {    
                        
                <form asp-route-id="@task.Id" asp-action="DeleteOrRecover" method="post" class=" col-md-7">
                    <a asp-route-id="@task.Id" asp-action="Update" class="btn btn-sm btn-default" >@SharedLocalizer["Change"]</a>
                    <button type="submit" class="btn btn-sm btn-danger">
                        @SharedLocalizer["Delete"]
                    </button>
                </form>
                <button  onclick='location.href = "@Url.Action("ExerciseSolutionsIndex", "ExerciseManagement", new { id = @task.Id})"' class="btn btn-sm btn-default col-md-3" >   @SharedLocalizer["Solutions"]</button>
}
                </td>
            </tr>
        }
        else
        {
            <tr style="background-color: rgba(126, 126, 126, 0.65)">
                <td style="color: #586272;">@task.Course</td>
                <td style="color: #738db5;"><a asp-action="TaskView" asp-route-id="@task.Id">@task.TaskName</a></td>
                <td>
                    @if (User.IsInRole("Teacher"))
                    {
                        <form asp-route-id="@task.Id" asp-action="DeleteOrRecover" method="post">
                            <button type="submit" class="btn btn-sm btn-warning">
                                @SharedLocalizer["Recover"] 
                            </button>
                        </form>
                    }
                </td>
            </tr>
        }
    }
</table>

WebApp/Views/ExerciseManagement/TaskView.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@inject IHtmlLocalizer<SharedRes> SharedLocalizer

@model WebApp.ViewModels.GetExerciseViewModel;
@{
    ViewBag.Title = "Task View";
}




<form asp-action="TaskView" asp-controller="ExerciseManagement">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <input type="hidden" asp-for="Id" id="TaskId" value="@Model.Id" />
    </div>
    <div class="form-group">
        <input type="text" asp-for="TaskName" class="form-control" readonly style="background-color: white;" />
    </div>
    <div class="form-group">
        <label class="control-label">@SharedLocalizer["Task"]:</label>
        <textarea asp-for="TaskTextField" id="MCE"></textarea>
    </div>
    <label asp-for="TaskBaseCodeField" class="control-label">@SharedLocalizer["BaseCode"]:</label>
    <textarea id="taskBaseCodeField" asp-for="TaskBaseCodeField" class="col-md-12" style="height: 400px; width: 100%;" readonly> </textarea>
    <br />
    <div class="col-md-1">
        <input value="@SharedLocalizer["Ok"]" onClick="history.go(-1)" ; class="btn btn-default" />

    </div>

</form>
<div class="col-md-1"></div>
<div class="col-md-2" style="margin-left: 10px;">
    <form asp-controller="Code" asp-action="Index">
        <input type="hidden" name="UserId" value="@User.Identity.Name" />
        <input type="hidden" name="ExerciseId" value="@Model.Id" />
        <button type="submit" class="btn btn-default">@SharedLocalizer["Start"]</button>
    </form>

</div>
<div style="clear: both;">
    <br />
</div>
<div>
    <button id="tggl" class="btn btn-default">@SharedLocalizer["Show/HideComments"]</button>

</div>

<div id="comments">
    <br />
    @foreach (var comment in Model.CommentList)
    {
        <div class="panel panel-info">

            <div class="panel-heading">
                @comment.UserName <span style="float: right;" class="rating" data-default-rating=@comment.Rating disabled></span>
            </div>
            <div class="panel-body">
                @comment.CommentText
            </div>
            <div class="panel-footer">
                @comment.CreationDateTime
            </div>
        </div>
    }
</div>


<div>
    <br />
    <div class="panel panel-warning" position: unset;">
        <div class="panel-heading ">
            <label class="control-label ">@SharedLocalizer["RateField"]</label>
            <span class="rating" id="rateField" data-default-rating="-1"></span>
        </div>
        <div class="panel-body ">
            <label class="control-label">@SharedLocalizer["ComText"]</label>
            <textarea style="width: 95%; margin-left: 20px;" id="textField" class="form-control"></textarea>
        </div>
        <div class="panel-footer">
            <button id="buttn" class="btn btn-default">@SharedLocalizer["Comment"]</button>
        </div>
    </div>
</div>

@section Scripts {



    <script>

        $('#buttn').click(
            function () {

                var comment = new Object();
                comment.ExerciseId = $('#TaskId').val();
                comment.Rating = qq;
                comment.CommentText = $('#textField').val();

                $.ajax({

                    type: "POST",
                    url: "/Comment/Create",
                    data: comment
                });
            });

        tinymce.init({ selector: '#MCE', readonly: 1, menubar: false, toolbar: false });

        var qq = 0;
        var ratings = document.getElementsByClassName('rating');

        for (var i = 0; i < ratings.length; i++) {
            var r = new SimpleStarRating(ratings[i]);

            ratings[i].addEventListener('rate', function (e) {
                console.log('Rating: ' + e.detail);
                qq = e.detail;
            });
        }

        $(document).ready(function () {
            $('#tggl').click(function () {
                $('#comments').toggle(900);
            });
        });

        var editableCodeMirror = null;
        window.onload = function () {
            editableCodeMirror = CodeMirror.fromTextArea(document.getElementById('taskBaseCodeField'), {
                mode: "text/x-csrc",
                theme: "default",
                lineNumbers: true
            });

        };

    </script>
}

WebApp/Views/ExerciseManagement/Update.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@inject IHtmlLocalizer<SharedRes> SharedLocalizer

@model WebApp.ViewModels.UpdateExerciseViewModel;
@{
    ViewBag.Title = "Task View";
}



<form asp-action="Update" asp-controller="ExerciseManagement">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <input id="TaskId" type="hidden" asp-for="Id" value="@Model.Id" />
    </div>
    <div class="form-group">
        <label asp-for="CourseId" class="control-label">@SharedLocalizer["CourseName"] *</label>
        <select asp-for="CourseId" id="CourseId" asp-items="@(new SelectList(Model.CourseList, "Id" , "Name" , 3))" class="form-control" required></select>
        <label asp-for="TaskName" class="control-label">@SharedLocalizer["TaskName"] *</label>
        <input type="text" asp-for="TaskName" id="TaskName" class="form-control" required />
    </div>
    <div class="form-group">
        <label class="control-label">@SharedLocalizer["Task"]:</label>
        <textarea asp-for="TaskTextField" id="MCE"></textarea>
    </div>
    <div>
        <button type="button" class="btn btn-success" id="runCode">►@SharedLocalizer["Run"]</button>
    </div>
    <div class="row">
        <div class=" col-md-6">
            <label class="control-label">@SharedLocalizer["BaseCode"]:</label>
            <textarea asp-for="TaskBaseCodeField" id="taskBaseCodeField" class="col-md-12" style="height: 400px; width: 100%;"></textarea>
        </div>

        <div>
            <label class="control-label">@SharedLocalizer["TestCasesCode"]:</label>
            <textarea asp-for="TestCases" id="testCasesCodeField" class="col-md-12" style="height: 400px; width: 100%;"></textarea>
        </div>
    </div>
    <div>
        <textarea id="result" style="padding: 10px; border-color: black; border: 1px solid; height: 100%; width: 100%; background-color: white" readonly="readonly"></textarea>
    </div>
    <br />
    <div class="form-group">
        <button id="save" class="btn btn-default">@SharedLocalizer["Save"]</button>
    </div>
</form>


<br />
<h6>@SharedLocalizer["Required"]</h6>

<script>
    tinymce.init({
        selector: '#MCE',
        plugins: [
            'advlist autolink list link image charmap print preview hr anchor pagebreak',
            'searchreplace wordcount visualblocks visualchars code fullscreen',
            'insertdatetime media nonbreaking save table contextmenu directionality',
            'emoticons template paste textcolor colorpicker textpattern imagetools image'
        ],
        toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
        toolbar2: 'print preview media | forecolor backcolor emotions | code',
        image_title: true,
        automatic_uploads: true,
        file_picker_types: 'image',
        file_picker_callback: function (cb, value, meta) {
            var input = document.createElement('input');
            input.setAttribute('type', 'file');
            input.setAttribute('accept', 'image/*');
            input.onchange = function () {
                var file = this.files[0];

                var reader = new FileReader();
                reader.onload = function () {
                    var id = 'blobid' + (new Date()).getTime();
                    var blobCache = tinymce.activeEditor.editorUpload.blobCache;
                    var blobInfo = blobCache.create(id, file, base64);
                    blobCache.add(blobInfo);

                    cb(blobInfo.blobUri(), { title: file.name });
                };
                reader.readAsDataURL(file);
            };
            input.click();
        }
    });


    window.onload = function () {
        var editableCodeMirror = CodeMirror.fromTextArea(document.getElementById('taskBaseCodeField'), {
            mode: "text/x-csrc",
            theme: "default",
            lineNumbers: true
        });

        var editableTestCasesCodeMirror = CodeMirror.fromTextArea(document.getElementById('testCasesCodeField'), {
            mode: "text/x-csrc",
            theme: "default",
            lineNumbers: true
        });

        $('#runCode').click(
            function () {
                $('#result').html('');
                var code = new Object();
                code.TestRunCode = editableTestCasesCodeMirror.getValue();
                code.TestRunCode += editableCodeMirror.getValue();
                $.ajax({
                    type: "POST",
                    url: "/Code/TestRun",
                    data: code,
                    success: function (data) {
                        $("#result").html(data);
                    }
                });
            }
        );
    };

    
</script>